name: "Doit"
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-42.1.beta <4.0.0'

dependencies:
  avatar_glow: ^3.0.1
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.1.1
  pulp_flash: ^0.0.6
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: MajorMonoDisplay
      fonts:
        - asset: fonts/MajorMonoDisplay-Regular.ttf

  assets:
    - assets/
    
